# Write your MySQL query statement below
SELECT PRODUCT_ID, YEAR 
AS FIRST_YEAR, QUANTITY, PRICE
 FROM (SELECT PRODUCT_ID,
  YEAR, QUANTITY,PRICE, rank() OVER(
   PARTITION BY PRODUCT_ID ORDER BY YEAR) RN
    FROM SALES ) _rank WHERE _rank.RN=1  ORDER BY PRODUCT_ID